version: '3.3'
services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: process.env.SELWYN_DB_DATABASE
      MYSQL_USER: process.env.SELWYN_DB_USER
      MYSQL_PASSWORD: process.env.SELWYN_DB_PASS
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: