CREATE DATABASE selwyn;

CREATE TABLE selwyn.events (
    id INT PRIMARY KEY AUTO_INCREMENT, 
    deleted BOOLEAN, 
    date DATE NOT NULL, name TEXT NOT NULL, place CHAR(50) NOT NULL, url CHAR(80) NOT NULL);

